blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions, general support, and help
    url: https://github.com/rshea0/enjinn/discussions/categories/help
    about: Are you having trouble figuring out how to use ENJINN? Please make a post on the help forum instead.
